### ISSUE TITLE
Purpose of references?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#116]
The `project` property `references` currently consists of an array with only one property: `url`:

https://github.com/tdwg/camtrap-dp/blob/92c53170a797b5b9784e1b01aa487d92614ef138/camtrap-dp-profile.json#L212-L222

I'm not entirely sure what the purpose of references is, but I assume it consists of a list of references that you cite in your project description and methods? However, you currently can't connect the two, as you only have a bunch of `urls`. I would add a property `reference`. Then at least you can do:

```
## project description

... see also Wearn & Glover-Kapfer (2017)

## references

[
  {
    "reference": "Wearn O & Glover-Kapfer P (2017) Camera-trapping for conservation: a guide to best-practices. WWF.",
    "url": "https://doi.org/10.13140/RG.2.2.23409.17767"
  }
]
```

Still, I'm not entirely convinced you need `references` as a separate property. It seems a lot easier to cite things in text with the url included:

```
Wearn & Glover-Kapfer (2017, https://doi.org/10.13140/RG.2.2.23409.17767)
```

**Comment by kbubnicki** [comment]
Yes, the purpose of this property is to provide a list of references (papers, websites etc) where you can learn more about given dataset. I agree that you can provide this information directly in the other text fields as `description` or `methods` but thinking ahead about the implementation of future camtrap data catalogues (web apps), a separate property (i.e. a list of references) will make this information easier to parse (automatically) and expose via dedicated UI.   
 
Good point with a missing property! I would only suggest to change `reference` to `title` as we already use this name in some other contexts.

**Comment by peterdesmet** [comment]
There might indeed be a use for data catalogues, however: if you would currently drop a Camtrap DP in a research repository like Zenodo, you would have to write the metadata in their editor (title, authors, description, references, etc.). All that info is then nicely published as DataCite metadata. So, I'm a bit reluctant to add non-technical metadata in the camtrap dp profile.

Otherwise, fine with using `title`.

**Comment by kbubnicki** [comment]
Actually, Zenodo is a good example when this property can be useful ;) You can use their API (https://developers.zenodo.org/#rest-api) to publish Camtrap DP dataset and then it is easier to directly map references as a property than parsing and searching for references in text fields (`description` or `methods`).

**Comment by kbubnicki** [comment]
@peterdesmet Please this PR: https://github.com/tdwg/camtrap-dp/pull/129

**Comment by ben-norton** [comment]
Since datasets are published at the project level, I suggest placing this field at the project level. 
The references field is critically important. It's the only mechanism that allows direct linkages between datasets, a fundamental component to the Linked Web (there are many names for this. See also Web 3.0, Semantic Web, etc.). URL should be unique references (dois are the perfect example). References could be links to pages on larger repositories (e.g., GBIF), alternate search engines (Online Collections portal https://collections.naturalsciences.org), APIs that include the dataset, project websites, etc.
Here's an example
Snapshot USA
Project Homepage: snapshot-usa.org (In Development)
Wildlife Insights Page:  https://app.wildlifeinsights.org/initiatives/2000156/Snapshot-USA
eMammal Page: https://emammal.si.edu/snapshot-usa
Paper: https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecy.3353
News Article: https://www.esa.org/blog/2021/07/14/snapshot-usa-first-ever-nationwide-mammal-survey-published/

This field also allows the more administratively complex projects to link to one another. Snapshot USA will soon become part of Snapshot Global, a larger global initiative. Data is published on an annual basis within Snapshot USA (2019, 2020, etc.). So Snapshot USA is the parent 'project' that is a child of the larger parent, Snapshot Global. Ideally, you could link to all of these when the annual dataset is published. Does that make sense?

**Comment by peterdesmet** [comment]
@ben-norton good point, but for that I’d rather have proper related identifiers (with a relationship) cf how DataCite/Zenodo are using. References are imo to provide full links to citations in the text.
