### ISSUE TITLE
`offspring` in lifeStage

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#213]
lifeStage has the values:

```
adult
subadult
juvenile
offspring
unknown
```

@kbubnicki How should the value `offspring` be interpreted?

**Comment by tucotuco** [comment]
I don't know where "offspring" is coming from, but it is not a good value for dwc:lifeStage. An offspring is a relationship, and can be any lifeStage. I recommended that values come from [this vocabulary](https://registry.gbif-uat.org/vocabulary/LifeStage), and if not there, that they be added and then come from there anyway.

**Comment by timrobertson100** [comment]
Nit: this vocabulary, not the UAT (test) one linked above:
https://registry.gbif.org/vocabulary/LifeStage

**Comment by peterdesmet** [comment]
@kbubnicki you added `offspring` in https://github.com/tdwg/camtrap-dp/commit/eda7e93b8e2aa43c7a0d40e22f9e9d6fbab201ba. Would you be fine if it is removed?

The 4 remaining values `adult`, `juvenile`, `unknown`, `subadult` all appear and are exactly the same as in https://registry.gbif.org/vocabulary/LifeStage (except not capitalized). The other values from https://registry.gbif.org/vocabulary/LifeStage are less applicable to camera trap data, so I suggest we keep recommending the reduced list of 4 values.

**Comment by peterdesmet** [comment]
> The only problem I see is that juvenile covers also individuals older than 1 year and the question is how to indicate that we observe individuals < 1 year?

@tucotuco @pzermoglio any advise on a term for that?

**Comment by ben-norton** [comment]
Followup to @tucotuco 
Lifestage has larger implications beyond camera trapping which could and most likely will lead to misinterpretations. Our Herp Collections use the following values for lifestage (standardization took considerable work)
Egg(s)
Eft(s)
Embryo(s)
Larva(e)
Paedomorph(s)
and half a dozen others. I think we should stick to what we can determine with confidence from a photo within the context of camera trapping. It's very hard if not impossible to say an animal is less than a year old because your fixing it to a number. However you can differentiate between a juvenile and adult, which is similar to lifestage (relative age) but not a skos exact match. Therefore it should be labeled differently, then mapped to dwc:lifeStage. I don't age is appropriate because age implies a numerical value  Give me a couple days and I can word this all more coherently, but hopefully the intent is understood.
.

**Comment by jimcasaer** [comment]
We had this discussion already several times within the team. The fact is that it depends on the species what age/lifestage classes can be differentiated. It also depends on the moment of the year. Given that the aim is to have classes that can be used for all species I think the only solution is to use 0 - 12months (juv), 12-24months (sub-adult), > 24 months adult. Whenever we have projects that need other classes we use the comments. E.g. in a recent project whenever piglets of wild boar were present we typed piglets:# in the comments

**Comment by peterdesmet** [comment]
@kbubnicki is that an acceptable solution for you (remove `offspring`, provide any more information in comments)?

**Comment by ben-norton** [comment]
I think we should remove "unknown". If you don't know, then leave it blank. Unless there's a scenario where someone would want to know all of the "unknowns". This may be overly audacious, but if you don't know something, then it's probably not fit for reuse and shouldn't be published.

**Comment by peterdesmet** [comment]
@ben-norton thanks for your note, I reposted it in an issue specifically regarding `unknown` (#212) so that we can tackle the `offspring` question in this issue.
