### ISSUE TITLE
Revise comments

### ISSUE THREAD

**Issue by ben-norton** [tdwg/camtrap-dp#221]
In several locations, the comments field is referenced as a location to provide information when 'other' is selected for a given field. Using a single field to capture multiple types of information for different purposes is problematic. Instead of a narrow defined purpose, there's an overlap of multiple fields without a clear way to relate information back to a field. 
An example. Let's say a large dead log is a feature in the detection zone of a given deployment. 'Dead log' isn't an option. So the 'other' option is chosen. The comments field already contains several notes associated with various aspects of the deployment. So the 'dead log' feature is added to the end. That information is nearly impossible to parse out. So for searching and indexing the records, the other description is of limited use. 
The comments field should have a specific purpose or narrow focus. A catchall for the 'other' options should be avoided. 
I don't think the answer is to add a featureTypeOther text field or even a featureTypeComments field. Rather, the feature type controlled vocabulary should be re-evaluated to determine if the other option can be eliminated altogether.

**Comment by peterdesmet** [comment]
>  If other, more info can be provided in the comments field.

I think this is fine for a controlled vocabulary where `other` is rather rare. If we're still missing many relevant terms, then I agree that is an issue. Maybe we should nudge people to suggest relevant missing terms to Camtrap DP?

**Comment by peterdesmet** [comment]
For reference, this applies to the terms [baitUse](https://tdwg.github.io/camtrap-dp/data/#deployments.baituse) and [featureType](https://tdwg.github.io/camtrap-dp/data/#deployments.featuretype)

**Comment by peterdesmet** [comment]
## Other

> @ben-norton: In several locations, the comments field is referenced as a location to provide information when 'other' is selected for a given field.

Solved: the term `other` is now removed from `baitUse` (now a boolean) and `featureType`, see #22. The comments field is only referenced in `baitUse` as:

> `true` if bait was used for the deployment. More information can be provided in `tags` or `comments`.

## Parsing info

> @ben-norton: The comments field already contains several notes associated with various aspects of the deployment. So the 'dead log' feature is added to the end. That information is nearly impossible to parse out. So for searching and indexing the records, the other description is of limited use.

Agree, which is why the `tags` field is suggested for more info on `baitUse`. Tags are more structured than comments:

> Formatted as a pipe (`|`) separated list for multiple values, with values optionally formatted as `key:value` pairs.
> Example: `forest edge | bait:food`

We still mention the `comments` field in `baitUse`, since people might have unstructured information regarding bait that they want to share as well (but not intended to be parsed by machines), for which the comment field is fine.

@ben-norton in my opinion this should sufficiently address your concern? I will close this issue. Let me know if you don't agree.
