### ISSUE TITLE
Why is `taxonID` currently not required in `observations.csv`?

### ISSUE THREAD

**Issue by Rafnuss** [tdwg/camtrap-dp#229]
It seems like `taxonID` is not required according to the documentation (https://tdwg.github.io/camtrap-dp/data/#observations), but it seems like that would be a required field, no? Maybe I'm missing something? 

https://github.com/inbo/camtraptor/pull/145#discussion_r952965544

**Comment by peterdesmet** [comment]
@Rafnuss I just remember why that is. 😄  Observations can contain `blank`, `unclassified`, `vehicle` "observations" that would not have any taxonomic information associated with it, which is why we can't make it a required term. When it does concern an observation of an animal, it is expected (but not validated) that `taxonID` is provided.
