### ISSUE TITLE
Consider renaming relationship types

### ISSUE THREAD

**Issue by tucotuco** [tdwg/camtrap-dp#260]
https://github.com/tdwg/camtrap-dp/blob/b13d541f137de43a238bed1153249ad20171a481/example/datapackage.json#L261

and

https://github.com/tdwg/camtrap-dp/blob/b13d541f137de43a238bed1153249ad20171a481/example/datapackage.json#L267

One might expect properties that begin with "Is" to signify an expected boolean value. Consider dropping the "Is" to make "derivedFrom" and "supplementTo".

**Comment by peterdesmet** [comment]
Thanks for the suggestion, but [these types](https://tdwg.github.io/camtrap-dp/metadata/#relatedidentifiers.relationtype) are borrowed wholesale from DataCite, which is why the term has an `skos:exactMatch` to https://schema.datacite.org/meta/kernel-4.4/include/datacite-relationType-v4.xsd.  For compatibility, I would not rename them.

Closing as `wontfix`
