### ISSUE TITLE
Rephrase definition for detectionDistance

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#265]
[detectionDistance](https://tdwg.github.io/camtrap-dp/data/#deployments.detectiondistance) is currently defined as:

> Furthest distance at which the camera detected a human during setup.

Can this be rephrased to:

> Furthest distance at which the camera detects activity, i.e. a human during setup.

@yliefting @kbubnicki

**Comment by yliefting** [comment]
Not exactly. We use detectionDistance to indicate the distance at which the camera still reliably detects a human moving around. while hand waving. Typically in walktest mode of the camera. So, I prefer:

> Maximum distance at which a human moving in front of the camera is reliably detected by the camera.

**Comment by ben-norton** [comment]
Why restrict the definition to humans? I think a better definition would be something like the maximum distance from the camera that target movement can trigger a capture event. They key is the maximum distance that something can trigger the capture event with movement. I know this is often determined by a human during setup, but that's the measurement technique, not what's actually being measured. Otherwise, you are scoping the definition to a single target type. Does that make sense?

**Comment by PietrH** [comment]
I agree with you Ben that the definition is scoped to a single target type, but that might not be a bad thing. 

I suspect you can't reliably predict sensor trigger reliability on distance alone, but also on other factors like the speed and size of the moving object, especially on the extreme of the detection range. 

So where it might be able to reliably detect a human at x meters, it might have trouble with something smaller, or maybe it can't detect a human at x meters, but it can an elephant walking in the field of view. It makes sense to me to use some sort of informal standard of describing the detectionDistance for the deployment. And since humans are usually on hand, that seems convenient. 

> the maximum distance from the camera that target movement can trigger a capture event

Wouldn't you end up with humans being used to measure this distance anyway?

**Comment by peterdesmet** [comment]
@PietrH exactly, you typically would end up using humans to measure this distance anyway. Could rephrase to:

> Maximum distance at which a camera can reliably detect activity, typically measured by having a human move in front of the camera.

@yliefting @kbubnicki up to you if we should _restrict_ the definition to a human moving in front of the camera, to avoid differences in measurement techniques.
