### ISSUE TITLE
Link `cameraHeight` to `dwc:minimumDistanceAboveSurfaceInMeters`

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#359]
As mentioned in https://github.com/tdwg/camtrap-dp/issues/353#issuecomment-1762260436, [cameraHeight](https://camtrap-dp.tdwg.org/data/#deployments.cameraHeight):

> Height at which the camera was deployed. Expressed in meters.

... is the equivalent of Darwin Core's:

- https://dwc.tdwg.org/terms/#dwc:minimumDistanceAboveSurfaceInMeters
- https://dwc.tdwg.org/terms/#dwc:maximumDistanceAboveSurfaceInMeters

> The lesser distance in a range of distance from a reference surface in the vertical direction, in meters. Use positive values for locations above the surface, negative values for locations below. If depth measures are given, the reference surface is the location given by the depth, otherwise the reference surface is the location given by the elevation.

How cameraHeight is an exact match with those terms:
- It is the vertical distance above a surface
- It is expressed in meters
- Positive value mean above

How cameraHeight is narrower than those terms:
- It indicates the height of a camera
- It only allows positive values

How cameraHeight is broader than those terms:
- It is expressed as single value, rather than 2

I'm inclined overal to consider it either an exact or narrower match, leaning more to narrower. @tucotuco would you agree? If so, I'll map to both minimumDistanceAboveSurfaceInMeters and maximumDistanceAboveSurfaceInMeters as broader concepts.

**Comment by tucotuco** [comment]
I don't think the fact that cameraHeight indicates the height of the camera
makes cameraHeight narrower than either of the other two terms. The other
two terms refer to a Location, not to a Location of a particular kind of
thing.

I also don't think the constraint (>0) makes it narrower either. That
arises simply by a physical restriction of the deployment in the real world.

Thus, I think cameraHeight is broader than either of the other two terms.

**Comment by peterdesmet** [comment]
Ok, not narrower. Could we perhaps consider this an `exactMatch`? Or is better to consider it broader?

**Comment by tucotuco** [comment]
If there was a term `verbatimDistanceAboveSurface` there could be a `skos:exactMatch` to that. Since there isn't, and `cameraHeight` is syntactically broader than the above surface terms, I think `cameraHeight` has to have a syntactic relationship of `skos:broadMatch` to each of the above surface terms.  This would be consistent with the [MIxS](https://github.com/tdwg/gbwg/blob/v2.1.0/dwc-mixs/mapping/DwC-MIxS_mappingSyntactic-2.0.0.sssom.tsv#L54) mapping of the above surface terms to `alt` for altitude.

**Comment by ben-norton** [comment]
I agree. There (should be) is a high bar for an exact match because it's transitive (x = y, y = z, then x = z must be true). One note, the height (or depth) of the camera has implications for modeling efforts that are not shared by collecting height/depth. If you mix camera height with collection height, you may lose that context. An exact match would allow that to occur. A broad match would not.
