### ISSUE TITLE
Wildlife Insights meta-data template

### ISSUE THREAD

**Issue by niconoe** [tdwg/camtrap-dp#57]
In GitLab by @Tim-Hofmeester on Sep 22, 2020, 13:14

Hej! 

You might already be aware of this, but here is a batch upload template for the meta-data standards as used by Wildlife Insights: https://docs.google.com/spreadsheets/d/1RCrg5guiNDYUkCijCSUgFvLwMQsCNf8DNUTaPddzAU0/edit#gid=862413563

Might be interesting to check (haven't have the time yet to compare the two).

**Comment by niconoe** [comment]
In GitLab by @kbubnicki on Sep 26, 2020, 13:01

Thanks @Tim-Hofmeester ! Actually, when I was drafting the very first version of these schemas I checked most of the existing metadata templates including the above one i.e. proposed by Wildlife Insights. But it is good to keep in mind that this particular template is already in use. Maybe it would be useful to create sth like a wiki page in this repository to summarize all existing proposals/templates that are already in use? (I have a short list already compiled)

**Comment by peterdesmet** [comment]
Now that we are aligning our efforts with @ben-norton, I think we can close this issue? @ben-norton?

**Comment by rondlg** [comment]
One question where will the discussion/information on the integration with WI be? Is the a wiki page I missed?

**Comment by ben-norton** [comment]
1. There is not a wiki page anywhere, nor is the WI data model publically documented anywhere at this time.
2. The upload templates are available. However, there are differences between the upload templates, data model, and front-end interface. Since they don't match, the output is different than the input. So the upload templates should not be used for mapping to Camtrap-DP.
3. There are a few technical details to work out before WI can be fully mapped to something like Camtrap-DP. 
4. Despite 1-3, I think a wiki page for WI integration is a good idea. Its just best to manage expectations at this time.

**Comment by rondlg** [comment]
Thankyou and most definitely.

**Comment by ben-norton** [comment]
I'm opting to close this issue. I think this topic has evolved significantly since June 2021. The context and content of the original issue are no longer relevant and hence the issue should be closed.
